# Generated by Django 4.1.2 on 2022-10-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
